prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    podMonitorSelector: {}
    ruleSelector: {}
    serviceAccountName: "prometheus-sa"

alertmanager:
  enabled: true
  alertmanagerSpec:
    serviceAccountName: "alertmanager-sa"

server:
  service:
    type: NodePort
    nodePort: 32000

grafana:
  enabled: false # set up separately
