loki:
  enabled: true
  service:
    type: NodePort
    nodePort: 31000
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  storage:
    type: s3
    s3:
      bucket: eks-loki-dev
      endpoint: s3.ap-south-2.amazonaws.com
      region: ap-south-2
      access_key_id: YOUR_ACCESS_KEY_ID  # Replace with your actual access key
      secret_access_key: YOUR_SECRET_ACCESS_KEY  # Replace with your actual secret key
      insecure: false  # Set to true if you don't want to use SSL
    schemaConfig:
      configs:
        - from: 2023-01-01
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: loki_index_
            period: 168h  # Adjust based on your retention policy
  auth_enabled: false  # Set to true if authentication is required

