loki:
  enabled: true
  service:
    type: NodePort
    nodePort: 31000
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  storage:
    bucketNames:
      chunks: "eks-loki-dev"
    s3:
      endpoint: http://eks-loki-dev.s3-website.ap-south-2.amazonaws.com
      region: ap-south-2
      access_key: AKIAS4PZBTETGA3WGC4W
      secret_key: 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