apiVersion: v2
name: loki-stack
description: A Helm chart for Loki
version: 0.1.0
appVersion: "2.6.1"
dependencies:
  - name: loki
    version: 2.6.1
    repository: https://grafana.github.io/helm-charts
