grafana:
  enabled: true
  sidecar:
    datasources:
      label: ""
      labelValue: ""
      enabled: true
      maxLines: 1000
  image:
    tag: latest
  service:
    type: NodePort        # Change service type to NodePort
    nodePort: 30000       # Specify the NodePort for Grafana (optional, can be auto-assigned)